### ISSUE TITLE
#15 Feat: 출석 API 구현

### ISSUE THREAD

**Issue by huncozyboy** [Leets-Official/Weeth-BE-Legacy#15]
### 출석 UI
- [x] 일정 제목
- [x] 날짜, 시간
- [x] 장소
- [x] 출석률
- [x] 결석률

### 출석 코드 생성
- [x] 난수로 4자리 수의 출석 코드 생성 로직
- [x] 코드의 유효기간 설정(30분)

### 출석 확인
- [x] 출석 코드 입력 받는 로직 
- [x] 출석 코드를 해당일자에 생성된 난수와 비교 후 출석, 결석 처리 로직 

### 예외처리
- [x] 사용자를 찾을 수 없을때(인증되지 않은 사용자)
- [x] 출석 요청 해당 시간에 동아리 모임이 존재하지 않을때
- [x] 출석 코드를 잘못 입력했을때

**Comment by jwnnoh** [comment]
이슈명 수정 부탁드립니다~!!
